services:
  mysql:
    image: mysql:8.0
    container_name: express_bd_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_rest
      MYSQL_USER: api_user
      MYSQL_PASSWORD: api123

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: express_bd_phpmyadmin
    restart: unless-stopped

    depends_on:
      - mysql

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8080:80"

volumes:
  mysql_data: